// <auto-generated />
namespace EmployeeInfo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedBranchNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedBranchNew));
        
        string IMigrationMetadata.Id
        {
            get { return "201312121114461_AddedBranchNew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
