// <auto-generated />
namespace EmployeeInfo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201312041001502_NewTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
