// <auto-generated />
namespace EmployeeInfo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newFkey1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newFkey1));
        
        string IMigrationMetadata.Id
        {
            get { return "201312170606445_newFkey1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
